### ISSUE TITLE
Failed Files - Reason: Error extracting text from PDF

### ISSUE THREAD

**Issue by ValenteMendez** [pashpashpash/vault-ai#16]
Hi! I am running the code locally, and I keep getting the following error when trying to upload a PDF file: 

**Failed Files: Reason: Error extracting text from PDF**

Has anyone encountered this problem and knows how to solve it?

Thanks!

**Comment by mhphilip** [comment]
Same here

**Comment by pashpashpash** [comment]
I forgot to include this dependency in the README. You need to install poppler
Ubuntu:
sudo apt-get install -y poppler-utils
Mac:
brew install poppler

**Comment by ValenteMendez** [comment]
It worked, thank you!

**Comment by ValenteMendez** [comment]
It worked, thank you!
