### ISSUE TITLE
Document Size Issue

### ISSUE THREAD

**Issue by DuckyDough** [pashpashpash/vault-ai#2]
I'm having an issue persisting my embeddings to my vector DB. Whenever I upload a pdf or text file I hit a quote error
`Reason: Error getting embeddings: error, status code: 429, message: You exceeded your current quota, please check your plan and billing details.`

 I tried a 61MB pdf and then a 500kb txt file and both yielded the same error message. What size documents do you recommend? Do you prepare your data in any way before upload? Or is a paid plan for Pinecone needed to persist book-sized ( or larger) text files?

**Comment by pashpashpash** [comment]
Are you running it locally?

**Comment by DuckyDough** [comment]
Yep I am, provided my own api keys and managed to get the UI and server running.

**Comment by DuckyDough** [comment]
I added a payment method to my openai account and this seems to have resolved the quota issue. 
However, now when I try the same files I hit a `2023/04/18 12:46:55 [UploadHandler ERR] Error upserting embeddings to Pinecone: Post "quickstart-*******.us-east4-gcp.pinecone.io/vectors/upsert": unsupported protocol scheme ""`
I can raise a separate issue if you'd prefer

**Comment by DuckyDough** [comment]
The unsupported protocol scheme issue was solved by prepending https:// to the pinecone endpoint address. The app is working correctly. Thank you
