### ISSUE TITLE
Increase token length of 8191

### ISSUE THREAD

**Issue by paOol** [pashpashpash/vault-ai#28]
after increasing `MAX_FILE_SIZE` and `MAX_TOTAL_UPLOAD_SIZE` in  `fileupload.go` , 
I uploaded an epub and after a while ran into this error.

The book is 45mb.

```
^[[?1;0c^[[?1;0c^[[?1;0c^[[?1;0c^[[?1;0c^[[?1;0c2023/04/20 09:01:19 [UploadHandler ERR] Error getting embeddings: error, status code: 400, message: This model's maximum context length is 8191 tokens, however you requested 8230 tokens (8230 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.
[negroni] Apr 20 08:54:39 | 200 | 6m40.613778887s
          POST /upload
          ```

is there a way to increase the amount of tokens, or chunk them appropriately for larger files?

**Comment by pashpashpash** [comment]
@paOol this should be fixed now https://github.com/pashpashpash/vault-ai/commit/2bff1759dc64e0ae16be23c410f20b14c725c1ec
