### ISSUE TITLE
Error upserting embeddings to Pinecone

### ISSUE THREAD

**Issue by tjb4578** [pashpashpash/vault-ai#40]
Just got the site up and running locally on windows.  Whenever I try to upload a file, I either get a timeout after ~5 minutes or I receive the following error after a couple seconds.  I've tried both txt and pdf files but am getting the same result.
```
Total chunks: 144
Total embeddings: 144
Embeddings length: 1536
2023/04/22 11:01:23 [upsertEmbeddingsToPinecone] Created pinecone upsert request with namespace =  78de054e-37fd-4669-9922-8dc1c8267755
2023/04/22 11:01:24 [UploadHandler ERR] Error upserting embeddings to Pinecone:
[negroni] Apr 22 11:01:21 | 200 | 3.0222837s
          POST /upload
```

**Comment by ms6rb** [comment]
this seems to be a problem with Pinecone's starter plan. I spent a lot of time trying to get around this error but ended up figuring out that I can't use the API at all. try any request with your API key, and you will probably get 403 or 401 errors.
https://docs.pinecone.io/docs/manage-data#connect

all we can do is wait for Pinecone to fix this issue or decide what will they do with the starter plan.

**Comment by tjb4578** [comment]
You're right, just tried a postman request and got a 403.  Weird how Pinecone doesn't mention API at all in their pricing, I kind of just assumed it'd be included in their starter plan.
