### ISSUE TITLE
Am I supposed to see "Enter your OpenAI API key here.." field on http://localhost:8100/ ?

### ISSUE THREAD

**Issue by mmmikko** [pashpashpash/vault-ai#80]
After some problems I managed to run the server - but not like in the README.md , the page at localhost has additional field for OpenAI API key. Is this supposed to happen, as the pictures in instructions do not have that field?

I could not get the server to start with "npm start", so I used "go run vault-web-server/main.go", which seemed to work fine.

With or without providing the API key the memory is not functioning, the response is always just "Great, what can I assist you with?".
Here is output from the server:
...
2023/05/19 22:09:14 [upsertEmbeddingsToPinecone] Created pinecone upsert request with namespace =  (redacted)
2023/05/19 22:09:14 Successfully added pinecone embeddings!
[negroni] May 19 22:02:54 | 200 | 6m19.876298409s
          POST /upload
2023/05/19 22:19:10 [QuestionForm] Validated: What is vault-ai?
2023/05/19 22:19:10 [QuestionHandler] Question: What is vault-ai?
2023/05/19 22:19:10 [QuestionHandler] Model: GPT Turbo
2023/05/19 22:19:10 [QuestionHandler] UUID: (redacted)
2023/05/19 22:19:10 [QuestionHandler] ApiKey: (redacted)
2023/05/19 22:19:10 [QuestionHandler] Using provided custom API key: (redacted)
2023/05/19 22:19:12 [retrieve] Querying pinecone namespace: 1bd4e..(redacted)
2023/05/19 22:19:13 [QuestionHandler] Got matches from Pinecone: []
2023/05/19 22:19:13 [QuestionHandler] Retrieved context from Pinecone:
 []
2023/05/19 22:19:13 [QuestionHandler] Sending OpenAI api request...
Prompt:
2023/05/19 22:19:15 [QuestionHandler] OpenAI response:
 Great, what can I assist you with?
[negroni] May 19 22:19:10 | 200 | 4.770990359s
          POST /api/questions
[negroni] May 19 22:19:40 | 200 | 381.056µs
          GET /

**Comment by pashpashpash** [comment]
This was fixed in the latest round of updates – the custom api field was removed
